Revert "Makefile: Enable MLGO compiler optimizations for regalloc and inlining"
ZyClang isn't compatible.

error: Requested regalloc eviction advisor analysis could not be created. Using
default
1 error generated.

This reverts commit b91c43e9120d9bb58278706fb8f618ed90e38d8c.